### ISSUE TITLE
about the top-down RGB image

### ISSUE THREAD

**Issue by xuxiaoxxxx** [AlexDelitzas/3D-VQA#2]
How do you to form the top-down RGB image? Is it a bev view? 
I took a tentative look at the point cloud and find that is too sparse. 
Can you share your method to me?

**Comment by AlexDelitzas** [comment]
Hi @xuxiaoxxxx ,

Thanks for your interest in our work! You can check how we render the top-down RGB images of the scenes [here](https://github.com/AlexDelitzas/3D-VQA/blob/main/run_generate.py) and [here](https://github.com/AlexDelitzas/3D-VQA/blob/main/generate_top_down.py).
